package ideaeclipse.DiscordAPINEW.webSocket;

public enum DispatchType {
    MESSAGE_CREATE, PRESENCE_UPDATE,
    CHANNEL_CREATE, CHANNEL_UPDATE, CHANNEL_DELETE,
    GUILD_ROLE_UPDATE, GUILD_ROLE_CREATE, GUILD_ROLE_DELETE,
    GUILD_MEMBER_ADD, GUILD_MEMBER_UPDATE, GUILD_MEMBER_REMOVE
}
